[phases.setup]
nixPkgs = ["...", "chromium"]

[phases.build]
cmds = ["cd client && npm install && npm run build", "cd server && npm install"]

[phases.deploy]
startCmd = "cd server && npx prisma migrate deploy && node index.js"
