[phases.setup]
nixPkgs = ["nodejs", "chromium", "fontconfig", "freetype", "dejavu_fonts", "liberation_ttf"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[phases.deploy]
startCmd = "npm start"
