[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && npx prisma migrate deploy && node index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[nixpacks]
# Install chromium for puppeteer
plan = { providers = ["node"], packages = ["chromium"] }
