[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[nixpacks]
plan = { providers = ["node"], packages = ["chromium", "fontconfig", "freetype", "dejavu_fonts", "liberation_ttf"] }
